[package]
name = "mnn-js"
version = "0.1.0"
edition = "2021"

[dependencies]
js-sys = "0.3.69"
mnn = { version = "0.1.0", path = ".." }
wasm-bindgen = "0.2.92"
web-sys = "0.3.69"

[lib]
crate-type = ["cdylib"]
